trigger:
  branches:
    include:
    - '*'
    
pool:
  vmImage: ubuntu-latest

container: ghcr.io/1alphabyte/nodedetabuild:latest
steps:
  - script: |
      sudo pnpm install
      sudo pnpm run build
    displayName: "Install dependencies and Build Astro project"
  - script: |
      echo "{\"access_token\":\"$(SPACE_ACCESS_TOKEN)\"}" | sudo tee /root/.detaspace/space_tokens
      sudo mv .space Spacefile ./dist
      sudo chmod -R 777 ./dist
      cd ./dist
      sudo /root/.detaspace/bin/space push
    displayName: "Deploy to Deta"