trigger:
  branches:
    include:
    - '*'
    
pool:
  vmImage: ubuntu-latest

variables:
  pnpm_config_cache: $(Pipeline.Workspace)/.pnpm-store

steps:
  - task: Cache@2
    inputs:
      key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
      path: $(pnpm_config_cache)
    displayName: Cache pnpm
  - task: UseNode@1
    inputs:
      version: '21.x'
  - script: |
      corepack enable
      corepack prepare pnpm@latest-8 --activate
      pnpm config set store-dir $(pnpm_config_cache)
    displayName: "Setup pnpm"

  - script: |
      pnpm install
      pnpm run build
    displayName: "Install dependencies and Build Astro project"
  - task: AzureStaticWebApp@0
    inputs:
      app_location: 'dist'
      skip_app_build: true
      skip_api_build: true
      is_static_export: true
      production_branch: "main"
      azure_static_web_apps_api_token: '2619df88451b09ba548847a8e4164fb2172caabe15b2ea51f72eaa5d870664184-50160537-991f-4f5a-b6f1-3cfa95fc424f010331341'