trigger:
  branches:
    include:
    - '*'
    
pool:
  vmImage: ubuntu-latest
  container: ghcr.io/1alphabyte/nodedetabuild:latest

steps:
  - script: |
      pnpm install
      pnpm run build
    displayName: "Install dependencies and Build Astro project"
  - script: |
      echo "{\"access_token\":\"$(SPACE_ACCESS_TOKEN)\"}" > /root/.detaspace/space_tokens
      cat /root/.detaspace/space_tokens
      mv .space Spacefile ./dist
      cd ./dist
      space push
    displayName: "Deploy to Deta"